
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: lyricraft_api
  username: falcon

test:
  <<: *default
  database: lyricraft_api
  username: falcon

production:
  <<: *default
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['USERNAME'] %>
  port: 5432
  password: <%= ENV['PASSWORD'] %>
  host: <%= ENV['HOST'] %>
